{
 "title": "Parking Detector",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Votes Left Taken Vs Empty",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spots_taken_gauge_left_total{spot=\"Left\", otel_scope_name=\"parking-detector\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spots_empty_gauge_left_total{spot=\"Left\", otel_scope_name=\"parking-detector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Right Vokes Taken Vs Empty",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spots_taken_gauge_right_total{spot=\"Right\", otel_scope_name=\"parking-detector\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spots_empty_gauge_right_total{spot=\"Right\", otel_scope_name=\"parking-detector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Votes (Left)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "spots_taken_gauge_left_total{spot=\"Left\", otel_scope_name=\"parking-detector\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spots_empty_gauge_left_total{spot=\"Left\", otel_scope_name=\"parking-detector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Votes (Right)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "spots_taken_gauge_right_total", "legendFormat": "__auto" },
    {
     "expr": "spots_empty_gauge_right_total{otel_scope_name=\"parking-detector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of times spot was set to empty",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spots_empty_total{otel_scope_name=\"parking-detector\", spot=\"Left\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spots_empty_total{spot=\"Right\", otel_scope_name=\"parking-detector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of times spot was set to taken",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spots_taken_total{spot=\"Left\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spots_taken_total{spot=\"Right\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Confidence Left Spot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg_over_time(last_detection_confidence{spot=\"Left\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Confidence Right Spot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg_over_time(last_detection_confidence{spot=\"Right\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Script Memory (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(process_memory_bytes{name=\"python\", type=\"rss\"}) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Script CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{name=\"python\"}[1m])) * 100 / 4",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Script User vs System Time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mode)(process_cpu_seconds_total{name=\"python\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Script Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by(context_switch_type)(process_context_switches_total{name=\"python\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Script Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"parking-detector\"}"
    }
   ]
  },
  {
   "title": "Script Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "filters": [
      { "id": "ca28bcde", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Fluent-Bit Memory (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(process_memory_bytes{name=\"fluent-bit\", type=\"rss\"}) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fluent-Bit CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{name=\"fluent-bit\"}[1m])) * 100 / 4",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FluentBit Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "process_context_switches_total{name=\"fluent-bit\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}